### ISSUE TITLE
algolia search - UI

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#10]
Das algolia search sdk verwenden um die Suchergebnisse nach Eingabe in einem Textfeld anzuzeigen.

**Comment by Ari1012** [comment]
Hallo, 
unsere Gruppe (TeamDone) würde gerne dieses Issue bearbeiten. Namen und Matrikelnummern schicke ich dir im slack 
Lg Ari

**Comment by fabianhinz** [comment]
https://recipehandler.web.app/
