### ISSUE TITLE
algolia search - cloud function

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#11]
[algolia](https://www.algolia.com/) mit der Collection "recipes" aus dem Firestore "füttern". *Tipp* hier gibt es eine Vielzahl von Tutorials. Im Vordergrund steht die Entwicklung einer Cloud-Function, die Suche sollte jedoch auch im Frontend verwendbar sein. Das "hübschmachen" der Suchergebnisse findet in #10 statt

**Comment by Vicropht** [comment]
Unsere Gruppe (Victor, Lukas, Larissa, Siandra, Fabi) würde gerne diesen Issue bearbeiten

**Comment by Vicropht** [comment]
Done

**Comment by fabianhinz** [comment]
https://www.youtube.com/channel/UCsBjURrPoezykLs9EqgamOA
