### ISSUE TITLE
Einstiegskomponenten für alle Routes

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#12]
Nach Abschluss des Issues #6 als weiterführendes Issues. Für jede Route soll eine Einstiegskomponente entwickelt werden:
Home
Details
Create
Edit

**Comment by siried11** [comment]
Würde ich gerne mit Annika und Serhat übernehmen.

**Comment by fabianhinz** [comment]
@siried11 sehr gerne - schaut mal den aktuellsten Kommentar unter #6 an 😄

**Comment by suse1016** [comment]
Ich, Annika und Simon würden gerne diesen Issue übernehmen

**Comment by siried11** [comment]
Bei jeder Seite ein passendes Layout und Dummy-Texte
