### ISSUE TITLE
Theme erstellen

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#13]
Ziel des Issues ist es die vorhandenen Components von Material-UI zu überschreiben um ein eigenes "IIB-Theme"  zu definieren

**Comment by daol1011** [comment]
Hallo, unsere Gruppe würde gerne diese Aufgabe bearbeiten
LG Oliver

**Comment by fabianhinz** [comment]
- Startpunkt in der Projektvorlage ist die Datei `theme.ts`
- ui library hier --> https://material-ui.com/
- Komponenten überschreiben

## ToDo
1. Typography (eigene Font family für alle varianten mit heading und eigene font family für alle anderen varianten). Als Basis dient dabei google fonts --> https://fonts.google.com/ - es sollte aber nicht die font 'Roboto' verwendet werden.
1. color palette anpassen: https://material-ui.com/customization/color/#color
material.io/tools/color
