### ISSUE TITLE
ErrorBoundary

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#16]
Damit unsere Anwendung bei Fehlern keine komplett weiße Seite anzeigt sollte eine ErrorBoundary 
mit React implementiert werden.
Einen Bonuspunkt gibt es wenn der gefangene Fehler im firestore protokolliert wird.

**Comment by ewto1011** [comment]
Unsere Gruppe würde diese Aufgabe bearbeiten.
Grüße 
Tobias Ewald

**Comment by daol1011** [comment]
Hallo, unsere Gruppe würde gerne diese Aufgabe bearbeiten.
LG Oliver

**Comment by fabianhinz** [comment]
nützliche Quelle https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries
# ToDo:
- wenn die Anwendung abstürzt eine fallbackui anzeigen
- ggf. Icons ... eigene Ideen gerne gesehen
- optional eben die Protokollierung im firestore
