### ISSUE TITLE
Rezept löschen

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#18]
Ein Rezept um UI Elemente und Logik ergänzen, damit es wieder gelöscht werden kann

**Comment by wiju1013wj** [comment]
Hallo Fabian, 
wir würden uns gerne mit diesem Issue beschäftigen. 
Danke und viele Grüße

**Comment by fabianhinz** [comment]
- Dokumentation für firebase (firestore) hier: https://firebase.google.com/docs/firestore/manage-data/delete-data
- Anlegen von neuen Sammlungen (collections) über den Gruppennahmen erlaubt
