### ISSUE TITLE
Kürzlich hinzugefügte Rezepte

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#36]
auf der Startseite die neusten 6 Rezepte anzeigen. Eine Query sollte hierfür an den Firestore geschickt werden die folgendes berücksichtigt:
- Beschränkung auf 6 Dokumente
- Sortierung über das Datum
- collection --> 'recipes'

**Comment by kbosshammer** [comment]
Unsere Gruppe würde dieses Issue übernehmen, wie in Slack besprochen.
