### ISSUE TITLE
Routing der SPA

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#6]
via [react-router](https://reacttraining.com/react-router/web/guides/quick-start) routing in der SinglePageApplication ermöglichen. Der Link verweist auf die populärste routing library für das React Ökosystem. Die Installation könnt ihr überspringen.
Folgende Routes sind in der Anwendung zu definieren:
1. Home
1. Details
1. Create
1. Edit

**Comment by suse1016** [comment]
Ich und Annika Kuntz würden dieses Issue gerne machen

**Comment by fabianhinz** [comment]
@suse1016 dann hätte ich ganz gerne eine kurze Nachricht aller Teammitglieder samt Matrikelnummer in Slack
