### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#7]
Abnahmekriterium: Es ist via Code möglich sich in Firebase anzumelden (Email & Password). Ein Nutzer muss hierfür natürlich über die Firebase Console angelegt werden.
+2 Punkte wenn ein Logindialog existiert, der auf den aktuellen Zustand des Anwenders (Stichwort: Authentifizierung) reagiert

**Comment by annikakuntz** [comment]
Ich habe zwar noch keine Gruppe, aber ich würde gerne dieses Issue bearbeiten. Wenn noch eine andere Person Interesse hat, können wir gerne eine 2er Gruppe zusammen bilden :)

**Comment by fabianhinz** [comment]
> Ich habe zwar noch keine Gruppe, aber ich würde gerne dieses Issue bearbeiten. Wenn noch eine andere Person Interesse hat, können wir gerne eine 3er Gruppe zusammen bilden :)

Wenn noch **zwei** weitere Personnen ... 👍

**Comment by fabianhinz** [comment]
- https://firebase.google.com/docs/auth/web/password-auth

**Comment by fabianhinz** [comment]
@annikakuntz Firebase ist nun (#27 ) im Projekt integriert. Zugriff auf alle für uns relevanten Dienste von Firebase bietet das Objekt `FirebaseService`. Folgendes ändert sich beim Entwickeln mit dem sdk im Vergleich zur Vorlage von Google:

```js
// laut Dokumentation
firebase.auth().createUserWithEmailAndPassword('','')
// in unserem Projekt
FirebaseService.auth.createUserWithEmailAndPassword('', '')
```
