### ISSUE TITLE
SPA als PWA 

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/iib-swe-ws19#8]
Die Webanwendung um PWA-Funktionalitäten ergänzen. Offline Funktionalitäten sind nicht Teil dieses Issues, sehr wohl aber der Einsatz eines Service-Workers und das Anlegen eines Web App Manifest. 
Nützliche Quelle [google - web fundamentals](https://developers.google.com/web/progressive-web-apps)
Wenn bei registriertem Service worker auf Web Push Notifications zurückgegriffen wird, gibt es einen Bonuspunkt

**Comment by annikakuntz** [comment]
Ich habe zwar noch keine Gruppe, aber ich würde gerne dieses Issue bearbeiten. Wenn noch eine andere Person Interesse hat, können wir gerne eine 2er Gruppe zusammen bilden :)

**Comment by fabianhinz** [comment]
wird erst einmal auf Eis gelegt, da der Code für service worker und Notifications schon in der Vorlage drin ist...
